[package]

name = "magicball"
version = "0.0.1"
authors = ["Pavel Filonov <filonovpv@gmail.com>"]

[dependencies]
hyper = "0.6.4"
rand = "0.3"
rustc-serialize = "0.3.15"
log = "0.3"
env_logger = "0.3"